environment:
  JPL_WORKSPACEDEBUG: "true"
  JPL_WORKSPACEDEBUGTIMEOUT: 90

sqa_criteria:
   qc_style:
     repos:
       udocker:
         container: udocker-testing
         tox:
           tox_file: /udocker/tox.ini
           testenv:
              - pylint
   qc_coverage:
     repos:
       udocker:
         container: udocker-testing
         tox:
           tox_file: /udocker/tox.ini
           testenv:
              - cover
   qc_security:
     repos:
       udocker:
         container: udocker-testing
         tox:
           tox_file: /udocker/tox.ini
           testenv:
              - bandit
