config:
  project_repos:
    udocker:
      repo: 'https://github.com/indigo-dc/udocker.git'      
      branch: devel3
      
environment:
  JPL_WORKSPACEDEBUG: "true"
  JPL_WORKSPACEDEBUGTIMEOUT: 90      
      
sqa_criteria:
   qc_style:
     repos:
       udocker:
         container: udocker-testing
         tox:
           tox_file: /udocker/tox.ini
           testenv:
              - pylint            
   qc_security:
     repos:
       udocker:
         container: udocker-testing
         tox:
           tox_file: /udocker/tox.ini
           testenv:
              - bandit         
   qc_coverage:
     repos:
       udocker:
         container: udocker-testing
         tox:
           tox_file: /udocker/tox.ini
           testenv:
              - cover
