config:
  project_repos:
    udocker:
      repo: 'https://github.com/MartaCastro/udocker.git'      
      branch: setup_jenkins-pipeline-library 

sqa_criteria:
   qc_style:
     repos:
       udocker:
         container: udocker-testing
         tox:
           tox_file: /udocker/tox.ini
           testenv:
              - pylint    
   qc_coverage:
     repos:
       udocker:
         container: udocker-testing
         tox:
           tox_file: /udocker/tox.ini
           testenv:
              - cover
   qc_security:
     repos:
       udocker:
         container: udocker-testing
         tox:
           tox_file: /udocker/tox.ini
           testenv:
              - bandit
           
           
           
